-- 创建新扩展表 T_ENTRUSTMENT (存储原 T_ENTRUSTMENT 的字段)
CREATE TABLE T_ENTRUSTMENT (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键，与 JC_CORE_WT_INFO.WT_ID 一一对应
    WT_NUM VARCHAR2(64), -- 委托编号
    PROJECT_NAME VARCHAR2(255), -- 工程名称
    CLIENT_UNIT VARCHAR2(255), -- 委托单位
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    TESTER VARCHAR2(64), -- 检测人
    REVIEWER VARCHAR2(64), -- 复核人
    APPROVER VARCHAR2(64), -- 批准人
    COMMISSION_DATE DATE, -- 委托日期
    CLIENT VARCHAR2(64), -- 委托人
    CONSTRUCTION_PART VARCHAR2(255), -- 施工部位
    CONSTRUCTION_UNIT VARCHAR2(255), -- 施工单位
    BUILDING_UNIT VARCHAR2(255), -- 建设单位
    SUPERVISION_UNIT VARCHAR2(255), -- 监理单位
    WITNESS_UNIT VARCHAR2(255), -- 见证单位
    WITNESS VARCHAR2(64), -- 见证人
    TEST_CATEGORY VARCHAR2(64), -- 检测类别
    PROJECT_AREA VARCHAR2(255), -- 工程区域/地点
    BEIZHU VARCHAR2(500), -- 备注
    SAMPLE_NAME VARCHAR2(255), -- 样品名称
    
    -- 新增字段 (来自 T_ENTRUSTMENT)
    SAMPLE_NUMBER VARCHAR2(255), -- 样品编号
    SPEC VARCHAR2(255), -- 规格型号
    MANUFACTURER VARCHAR2(255), -- 生产厂家
    SAMPLE_QUANTITY VARCHAR2(255), -- 样品数量
    REPRESENTATIVE_BATCH VARCHAR2(255), -- 代表批量
    BATCH_NUMBER VARCHAR2(255), -- 批号
    CLIENT_ADDRESS_PHONE VARCHAR2(500), -- 委托单位地址及电话
    REPORT_SEND_MODE VARCHAR2(64), -- 报告发送方式
    REPORT_SEND_USER VARCHAR2(64), -- 报告发送人
    SAMPLE_DISPOSAL VARCHAR2(64), -- 样品处理方式
    DELIVERY_MODE VARCHAR2(64), -- 送样方式
    DELIVERY_DATE VARCHAR2(64), -- 送样日期
    FEE VARCHAR2(64), -- 费用
    SAMPLE_HISTORY VARCHAR2(2000), -- 样品历史
    SAMPLE_STATUS VARCHAR2(2000), -- 样品状态
    TEST_ITEMS VARCHAR2(2000), -- 检测项目
    WITNESS_ID_CARD VARCHAR2(64), -- 见证人身份证号
    SAMPLING_MAN_ID_CARD VARCHAR2(64), -- 取样人身份证号
    WT_MAN_SIGN CLOB, -- 委托人签名
    WT_REVIEWER VARCHAR2(64), -- 委托单审核人
    WT_REVIEW_SIGN CLOB, -- 委托单审核人签名
    REVIEW_SIGNATURE_PHOTO CLOB, -- 复核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB -- 批准人签名图片
);

-- 重建目录表
CREATE TABLE T_SIMPLE_DIRECTORY (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    DIR_ID VARCHAR2(64), -- 目录ID
    DIR_NAME VARCHAR2(255), -- 目录名称（通常为委托编号）
    TABLE1_TYPE VARCHAR2(64), TABLE1_ID VARCHAR2(64), -- 关联表1类型及ID
    TABLE2_TYPE VARCHAR2(64), TABLE2_ID VARCHAR2(64), -- 关联表2类型及ID
    TABLE3_TYPE VARCHAR2(64), TABLE3_ID VARCHAR2(64), -- 关联表3类型及ID
    TABLE4_TYPE VARCHAR2(64), TABLE4_ID VARCHAR2(64), -- 关联表4类型及ID
    TABLE5_TYPE VARCHAR2(64), TABLE5_ID VARCHAR2(64), -- 关联表5类型及ID
    TABLE6_TYPE VARCHAR2(64), TABLE6_ID VARCHAR2(64), -- 关联表6类型及ID
    TABLE7_TYPE VARCHAR2(64), TABLE7_ID VARCHAR2(64), -- 关联表7类型及ID
    TABLE8_TYPE VARCHAR2(64), TABLE8_ID VARCHAR2(64), -- 关联表8类型及ID
    TABLE9_TYPE VARCHAR2(64), TABLE9_ID VARCHAR2(64), -- 关联表9类型及ID
    TABLE10_TYPE VARCHAR2(64), TABLE10_ID VARCHAR2(64), -- 关联表10类型及ID
    STATUS NUMBER, -- 状态
    TESTER VARCHAR2(64), -- 检测人
    REVIEWER VARCHAR2(64), -- 复核人
    APPROVER VARCHAR2(64), -- 批准人
    WT_UNDERTAKER VARCHAR2(64), -- 委托承接人
    WT_REVIEWER VARCHAR2(64), -- 委托审核人
    JC_FILLER VARCHAR2(64), -- 检测记录填写人
    JC_TESTER VARCHAR2(64), -- 检测记录检测人
    JC_REVIEWER VARCHAR2(64), -- 检测记录审核人
    BG_TESTER VARCHAR2(64), -- 报告检测人（主检）
    BG_REVIEWER VARCHAR2(64), -- 报告审核人
    BG_APPROVER VARCHAR2(64), -- 报告批准人
    CREATE_MAN VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_MAN VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP -- 更新时间
);

-- 重建签名表
CREATE TABLE JZS_SIGNATURE (
    SIGNATURE_ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 签名ID
    USER_ACCOUNT VARCHAR2(64), -- 用户账号
    SIGNATURE_TYPE VARCHAR2(64), -- 签名类型
    SIGNATURE_BLOB BLOB, -- 签名数据
    IMAGE_TYPE VARCHAR2(64), -- 图片类型
    IMAGE_SIZE NUMBER, -- 图片大小
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_TIME TIMESTAMP, -- 更新时间
    REMARKS VARCHAR2(255) -- 备注
);

-- 重建各类试验数据表 (关联 JC_CORE_WT_INFO)
-- 统一结构：ID, ENTRUSTMENT_ID (关联 JC_CORE_WT_INFO.WT_ID), DATA_JSON 及各表特定字段

CREATE TABLE T_DENSITY_TEST (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    -- 业务字段
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB, -- 记录表审核人签名
    SOIL_TYPE VARCHAR2(64), -- 土样类型
    PIT_VOLUME NUMBER, -- 试坑体积
    WET_WEIGHT NUMBER, -- 湿土质量
    DRY_WEIGHT NUMBER, -- 干土质量
    WATER_CONTENT NUMBER, -- 含水率
    WET_DENSITY NUMBER, -- 湿密度
    DRY_DENSITY NUMBER, -- 干密度
    MAX_DRY_DENSITY NUMBER, -- 最大干密度
    MIN_DRY_DENSITY NUMBER, -- 最小干密度
    COMPACTION_COEFFICIENT NUMBER, -- 压实系数
    QUALIFIED_RATE NUMBER -- 合格率
);

CREATE TABLE T_NUCLEAR_DENSITY (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB -- 记录表审核人签名
);

CREATE TABLE T_SAND_REPLACEMENT (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB -- 记录表审核人签名
);

CREATE TABLE T_WATER_REPLACEMENT (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB -- 记录表审核人签名
);

CREATE TABLE T_CUTTING_RING (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB -- 记录表审核人签名
);

CREATE TABLE T_REBOUND_METHOD (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB, -- 记录表审核人签名
    STRUCTURE_PART VARCHAR2(255), -- 构件名称/部位
    CONCRETE_GRADE VARCHAR2(64), -- 混凝土强度等级
    MOLDING_DATE DATE, -- 成型日期
    AGE VARCHAR2(64), -- 龄期
    INSTRUMENT_MODEL VARCHAR2(128), -- 仪器型号
    CALIBRATION_NO VARCHAR2(128), -- 率定编号
    ZONE_COUNT VARCHAR2(64), -- 测区数量
    POURING_DIRECTION VARCHAR2(64), -- 浇筑方向
    TEST_ANGLE VARCHAR2(64), -- 测试角度
    PUMPING_METHOD VARCHAR2(64), -- 泵送方式
    PUMPING VARCHAR2(64), -- 是否泵送
    DESIGN_STRENGTH VARCHAR2(64), -- 设计强度
    CARBONATION_DEPTH VARCHAR2(64), -- 碳化深度
    TEST_RESULT VARCHAR2(500) -- 检测结果
);

CREATE TABLE T_LIGHT_DYNAMIC_PENETRATION (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    -- 业务字段
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB, -- 记录表审核人签名
    SOIL_PROPERTY VARCHAR2(200), -- 土质属性
    DESIGN_CAPACITY VARCHAR2(200), -- 设计承载力
    HAMMER_WEIGHT VARCHAR2(100), -- 锤重
    DROP_DISTANCE VARCHAR2(100), -- 落距
    TEST_BASIS VARCHAR2(500), -- 检测依据
    EQUIPMENT VARCHAR2(500), -- 检测设备
    CONCLUSION VARCHAR2(1000), -- 结论
    TEST_DATE DATE, -- 检测日期
    REPORT_DATE DATE, -- 报告日期
    DATA_BLOCKS CLOB, -- 数据块
    REMARKS VARCHAR2(1000) -- 备注
);

CREATE TABLE T_BECKMAN_BEAM (
    ID VARCHAR2(64) NOT NULL PRIMARY KEY, -- 主键
    ENTRUSTMENT_ID VARCHAR2(64), -- 委托单ID
    DATA_JSON CLOB, -- 扩展数据JSON
    STATUS VARCHAR2(64), -- 状态
    REJECT_REASON VARCHAR2(500), -- 退回原因
    NEXT_HANDLER VARCHAR2(64), -- 下一处理人
    TESTER_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片 (备用)
    REVIEW_SIGNATURE_PHOTO CLOB, -- 报告/结果审核人签名图片
    INSPECT_SIGNATURE_PHOTO CLOB, -- 报告/结果检测人签名图片
    APPROVE_SIGNATURE_PHOTO CLOB, -- 报告/结果批准人签名图片
    CREATE_BY VARCHAR2(64), -- 创建人
    CREATE_TIME TIMESTAMP, -- 创建时间
    UPDATE_BY VARCHAR2(64), -- 更新人
    UPDATE_TIME TIMESTAMP, -- 更新时间
    TESTER VARCHAR2(64), -- 报告/结果检测人
    REVIEWER VARCHAR2(64), -- 报告/结果审核人
    APPROVER VARCHAR2(64), -- 报告/结果批准人
    FILLER VARCHAR2(64), -- 填写人
    RECORD_TESTER VARCHAR2(64), -- 记录表检测人
    RECORD_TESTER_SIGN CLOB, -- 记录表检测人签名
    RECORD_REVIEWER VARCHAR2(64), -- 记录表审核人
    RECORD_REVIEW_SIGN CLOB -- 记录表审核人签名
);
