-- 测试查询JC_CORE_WT_INFO表
-- 1. 查看表结构
DESC JC_CORE_WT_INFO;

-- 2. 查询前10条记录，查看WT_NUM格式
SELECT WT_ID, WT_NUM, WT_UNIT, GC_NAME 
FROM JC_CORE_WT_INFO 
WHERE ROWNUM <= 10;

-- 3. 按特定WT_NUM查询（替换为你要查询的编号）
SELECT * 
FROM JC_CORE_WT_INFO 
WHERE WT_NUM = 'S-2024-36485';

-- 4. 模糊查询（如果不确定完整编号）
SELECT WT_ID, WT_NUM, WT_UNIT 
FROM JC_CORE_WT_INFO 
WHERE WT_NUM LIKE '%S-2024%';

-- 5. 统计记录数
SELECT COUNT(*) AS TOTAL_COUNT 
FROM JC_CORE_WT_INFO;
