-- 创建检测委托单表
CREATE TABLE JZS_ENTRUSTMENT (
    -- 基础信息字段
    UNIFIED_NUMBER VARCHAR2(50) PRIMARY KEY,
    SAMPLE_NUMBER VARCHAR2(50),
    CLIENT_UNIT VARCHAR2(200),
    CLIENT_DATE VARCHAR2(20),
    CONSTRUCTION_UNIT VARCHAR2(200),
    BUILDING_UNIT VARCHAR2(200),
    PROJECT_NAME VARCHAR2(200),
    CONSTRUCTION_PART VARCHAR2(200),
    SAMPLE_NAME VARCHAR2(200),
    SPEC VARCHAR2(200),
    MANUFACTURER VARCHAR2(200),
    SAMPLE_QUANTITY VARCHAR2(50),
    REPRESENTATIVE_BATCH VARCHAR2(200),
    BATCH_NUMBER VARCHAR2(100),
    TEST_CATEGORY VARCHAR2(100),
    CLIENT_ADDRESS_PHONE VARCHAR2(200),
    REPORT_SEND VARCHAR2(100),
    SAMPLE_DISPOSAL VARCHAR2(100),
    WITNESS VARCHAR2(100),
    WITNESS_UNIT VARCHAR2(200),
    DELIVERY_MODE VARCHAR2(50),
    DELIVERY_DATE1_Y VARCHAR2(10),
    DELIVERY_DATE1_M VARCHAR2(10),
    DELIVERY_DATE1_D VARCHAR2(10),
    DELIVERY_DATE2_Y VARCHAR2(10),
    DELIVERY_DATE2_M VARCHAR2(10),
    DELIVERY_DATE2_D VARCHAR2(10),
    FEE VARCHAR2(50),
    REMARKS VARCHAR2(500),
    SAMPLE_HISTORY VARCHAR2(500),
    SAMPLE_STATUS VARCHAR2(500),
    TEST_ITEMS VARCHAR2(500),
    
    -- 额外字段
    REVIEWER VARCHAR2(100),
    INSPECTOR VARCHAR2(100),
    APPROVER VARCHAR2(100),
    PAGE NUMBER,
    TOTAL_PAGES NUMBER,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR VARCHAR2(100),
    REVIEW_SIGNATURE_PHOTO VARCHAR2(500),
    INSPECT_SIGNATURE_PHOTO VARCHAR2(500),
    APPROVE_SIGNATURE_PHOTO VARCHAR2(500)
);

-- 创建轻型动力触探检测记录表
CREATE TABLE JZS_LIGHT_DYNAMIC_PENETRATION (
    -- 基础信息字段
    UNIFIED_NUMBER VARCHAR2(50) PRIMARY KEY,
    ENTRUSTING_UNIT VARCHAR2(200),
    PROJECT_NAME VARCHAR2(200),
    ENTRUST_DATE VARCHAR2(20),
    CONSTRUCTION_PART VARCHAR2(200),
    TEST_DATE VARCHAR2(20),
    SOIL_PROPERTY VARCHAR2(200),
    REPORT_DATE VARCHAR2(20),
    WITNESS_UNIT VARCHAR2(200),
    WITNESS VARCHAR2(100),
    DESIGN_CAPACITY VARCHAR2(50),
    HAMMER_WEIGHT VARCHAR2(50),
    DROP_DISTANCE VARCHAR2(50),
    TEST_CATEGORY VARCHAR2(100),
    TEST_BASIS VARCHAR2(500),
    EQUIPMENT VARCHAR2(500),
    REMARKS VARCHAR2(500),
    APPROVE VARCHAR2(100),
    REVIEW VARCHAR2(100),
    INSPECT VARCHAR2(100),
    COMPANY_NAME VARCHAR2(200),
    COMPANY_ADDRESS VARCHAR2(500),
    COMPANY_PHONE VARCHAR2(100),
    CONCLUSION VARCHAR2(1000),
    DATA_BLOCKS CLOB, -- 使用CLOB存储JSON数据
    
    -- 额外字段
    REVIEWER VARCHAR2(100),
    INSPECTOR VARCHAR2(100),
    APPROVER VARCHAR2(100),
    PAGE NUMBER,
    TOTAL_PAGES NUMBER,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR VARCHAR2(100),
    REVIEW_SIGNATURE_PHOTO VARCHAR2(500),
    INSPECT_SIGNATURE_PHOTO VARCHAR2(500),
    APPROVE_SIGNATURE_PHOTO VARCHAR2(500)
);

-- 创建索引
CREATE INDEX IDX_JZS_ENTRUSTMENT_SAMPLE ON JZS_ENTRUSTMENT(SAMPLE_NUMBER);
CREATE INDEX IDX_JZS_ENTRUSTMENT_CLIENT ON JZS_ENTRUSTMENT(CLIENT_UNIT);
CREATE INDEX IDX_JZS_LIGHT_DYNAMIC_PROJECT ON JZS_LIGHT_DYNAMIC_PENETRATION(PROJECT_NAME);
CREATE INDEX IDX_JZS_LIGHT_DYNAMIC_DATE ON JZS_LIGHT_DYNAMIC_PENETRATION(TEST_DATE);