-- 创建签字存放表
CREATE TABLE JZS_SIGNATURE (
    -- 主键
    SIGNATURE_ID VARCHAR2(36) PRIMARY KEY,
    
    -- 用户账号（外键，关联到JZS_USERS表的USER_ACCOUNT）
    USER_ACCOUNT VARCHAR2(36) NOT NULL,
    
    -- 签名类型（如：审核、检验、批准等）
    SIGNATURE_TYPE VARCHAR2(50) NOT NULL,
    
    -- 签名图片路径（存储在文件系统中的路径）
    SIGNATURE_PATH VARCHAR2(500),
    
    -- 签名图片二进制数据（如果直接存储在数据库中）
    SIGNATURE_BLOB BLOB,
    
    -- 签名图片类型（如：png、jpg等）
    IMAGE_TYPE VARCHAR2(20),
    
    -- 签名图片大小（字节）
    IMAGE_SIZE NUMBER,
    
    -- 创建时间
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- 更新时间
    UPDATE_TIME TIMESTAMP,
    
    -- 备注
    REMARKS VARCHAR2(500),
    
    -- 外键约束，关联到用户表
    CONSTRAINT FK_SIGNATURE_USER FOREIGN KEY (USER_ACCOUNT) REFERENCES JZS_USERS(USER_ACCOUNT)
);

-- 创建唯一索引，确保每个用户每种签名类型只有一条记录
CREATE UNIQUE INDEX UK_SIGNATURE_USER_TYPE ON JZS_SIGNATURE(USER_ACCOUNT, SIGNATURE_TYPE);

-- 创建普通索引，加速查询
CREATE INDEX IDX_SIGNATURE_TYPE ON JZS_SIGNATURE(SIGNATURE_TYPE);
CREATE INDEX IDX_SIGNATURE_CREATE_TIME ON JZS_SIGNATURE(CREATE_TIME);

-- 插入示例数据
INSERT INTO JZS_SIGNATURE (SIGNATURE_ID, USER_ACCOUNT, SIGNATURE_TYPE, SIGNATURE_PATH, IMAGE_TYPE, REMARKS)
VALUES ('1', 'admin', '审核', '/uploads/signatures/admin_review.png', 'png', '管理员审核签名');

INSERT INTO JZS_SIGNATURE (SIGNATURE_ID, USER_ACCOUNT, SIGNATURE_TYPE, SIGNATURE_PATH, IMAGE_TYPE, REMARKS)
VALUES ('2', 'admin', '检验', '/uploads/signatures/admin_inspect.png', 'png', '管理员检验签名');

INSERT INTO JZS_SIGNATURE (SIGNATURE_ID, USER_ACCOUNT, SIGNATURE_TYPE, SIGNATURE_PATH, IMAGE_TYPE, REMARKS)
VALUES ('3', 'admin', '批准', '/uploads/signatures/admin_approve.png', 'png', '管理员批准签名');

COMMIT;